### ISSUE TITLE
linux的代码是不是有问题?

### ISSUE THREAD

**Issue by timuxi** [Li-Zhaoxi/uart2net#1]
![image](https://user-images.githubusercontent.com/78781986/172082361-22cf5daf-01e8-4bf3-85d1-b881ce44f7b9.png)

**Comment by timuxi** [comment]
![image](https://user-images.githubusercontent.com/78781986/172083070-a95e1122-9c45-4b24-ac5f-19a37952ffc6.png)

**Comment by timuxi** [comment]
我是在树莓派上使用的

**Comment by Li-Zhaoxi** [comment]
@timuxi 你是不是没安装qt的串口包？执行下这个试试`sudo apt-get install libqt5serialport5-dev`

**Comment by timuxi** [comment]
> 

![image](https://user-images.githubusercontent.com/78781986/172095453-13145d2e-8c03-4050-aaca-fd4011b405da.png)
这是我执行`sudo apt-get install libqt5serialport5-dev`以后的结果

**Comment by Li-Zhaoxi** [comment]
@timuxi 奇怪了，你在uart2net的文件夹下用的qmake吧。如果方便的话，我远程下你电脑看看？

**Comment by timuxi** [comment]
@Li-Zhaoxi 19883106474 方便的话加个vx聊下

**Comment by Li-Zhaoxi** [comment]
低内存开发板，注意内存，1G内存要用make -j4。
